# Generated by Django 4.0.3 on 2023-01-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='mobile_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
