# Generated by Django 4.0.3 on 2023-01-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_ticket_history_aadhar_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='aadhar_no',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='sex',
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='mobile_number',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='customer',
            name='seatno',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='no_tkt',
            field=models.IntegerField(),
        ),
    ]
