# Generated by Django 4.0.3 on 2023-02-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_customer_destination_customer_price_customer_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='destination',
            field=models.CharField(default='Odisha', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='price',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='customer',
            name='source',
            field=models.CharField(default='Hyderabad', max_length=20),
        ),
    ]
