# Generated by Django 4.0.3 on 2023-02-08 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_passenger_destination_passenger_no_tkt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='User_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
