# Generated by Django 4.0.3 on 2023-02-09 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_passenger_bus_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='Passenger_name',
            new_name='name',
        ),
    ]
