# Generated by Django 4.0.3 on 2023-02-09 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_passenger_name_passenger_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='Age',
            new_name='age',
        ),
    ]
