# Generated by Django 4.0.3 on 2023-02-09 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_age_passenger_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='Seat_no',
            new_name='seatno',
        ),
    ]
